apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app-deployment
  labels:
    app: ai-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
        - name: ai-app-container
          image: divyeshsali/cicd-ai-app
          ports:
            - containerPort: 5000
