apiVersion: v1
kind: Service
metadata:
  name: ai-app-service
spec:
  type: NodePort
  selector:
    app: ai-app
  ports:               # ✅ chhota "p"
    - protocol: TCP
      port: 5000       # ✅ chhota "p"
      targetPort: 5000
